"use client";

export const LandingContent = () => {
  return (
    <div className="p-4  bg-orange-400 bg-opacity-25 rounded-lg backdrop-blur-md w-[80vw] mx-auto ">
      <h2 className="mb-2 text-3xl font-bold text-center text-red-600 ">
        Disclaimer
      </h2>
      <p className="text-[1.2vw] font-bold text-gray-300 text-justify ">
        This website was created as a portfolio piece for YacineL.com. While the
        website has a fully functioning monthly subscription but unfortunately,{" "}
        <span className="text-gray-600 bg-yellow-100">
          we DO NOT offer customer support and we CANNOT guarantee the
          continuation of this website in the distant future.
        </span>
        By using this website, you agree that we are not responsible for any
        damages or losses that may occur as a result of using our services. We
        do not make any warranties or representations about the accuracy or
        completeness of the content generated by our AI models. The content
        generated by our AI models is for informational purposes only and should
        not be relied upon for any critical purpose. We reserve the right to
        modify or discontinue our services at any time within a short notice.
      </p>
    </div>
  );
};
